apiVersion: '2019-12-01'
location: polandcentral
name: black-tool-llm
properties:
  volumes:
    - name: tool_llm_volume
      azureFile:
        shareName: toolllmfileshare
        storageAccountName: blackllm
        storageAccountKey: XkwtIQjuVj2jCC6re5z0TF0JG1zK+Svzo7ozzal79rVOtTOUEn126KLEn3m+Zccwox1wPTuhfN17+AStCsFEDA==    

  containers:
    - name: black-tool-llm-container
      properties:
        image: blacktoolllm.azurecr.io/docker-tool_llm:latest
        environmentVariables:
          - name: APP_DIR
            value: /black_tool_llm/app  
          - name: DATA_DIR
            value: /black_tool_llm/data  
          - name: UI_DIR
            value: /black_tool_llm/ui  

        resources:
          requests:
            cpu: 1.0
            memoryInGB: 1.5
      volumeMounts:
        - name: tool_llm_volume
          mountPath: /black_tool_llm  


  osType: Linux
  restartPolicy: Always

