version: '3'

services:
  tool_llm:
    build: tool_llm
    env_file:
      - .env
    environment:
      PORT: "${WEB_PORT}"
    ports:
      - "${WEB_PORT}:${WEB_PORT}"    
    volumes:
      - ${APP_DIR}:/app
      - ${DATA_DIR}:/llm_data
      - ${MODELS_DIR}:/llm_models
      - ${UI_DIR}:/llm_ui